---
title: "Insert svg files"
date: 2022-03-14
---
author: liwencongm
email: your-email@domain.com
theme: minima
description: > #Javascript 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
